logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework.boot.context.config: INFO

grpc:
  server:
    port: 9090
    # address: 0.0.0.0  # слушать все интерфейсы
  advice:
    exception-handling:
      enabled: true
      base-packages: omsu.inventory.exception
      ignored-exception-types:
        - io.grpc.StatusRuntimeException

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5437/inventorydb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: inventory_schema
---
spring:
  config:
    activate:
      on-profile: dev, staging
grpc:
  server:
    reflection:
      enabled: true   # Reflection для разработки

---
spring:
  config:
    activate:
      on-profile: prod
grpc:
  server:
    reflection:
      enabled: false     # Отключаем в проде