spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: secret
  flyway:
    schemas: inventory_schema
  kafka:
    bootstrap-servers: kafka:9092

grpc:
  server:
    port: 9090