logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework.boot.context.config: INFO
    org.springframework.kafka: DEBUG

grpc:
  server:
    port: 9090
  advice:
    exception-handling:
      enabled: true
      base-packages: omsu.inventory.exception
      ignored-exception-types:
        - io.grpc.StatusRuntimeException

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5437/inventorydb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: inventory_schema
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring:
  config:
    activate:
      on-profile: dev, staging
grpc:
  server:
    reflection:
      enabled: true   # Reflection для разработки

---
spring:
  config:
    activate:
      on-profile: prod
grpc:
  server:
    reflection:
      enabled: false     # Отключаем в проде