server:
  port: 8111

spring:
  application:
    name: rest-client
grpc:
  client:
    inventory-service:
      address: static://localhost:9090
      negotiation-type: plaintext
    order-service:
      address: static://localhost:9090
      negotiation-type: plaintext
logging:
  level:
    org.springframework.grpc: INFO
    io.grpc: DEBUG
    io.grpc.netty: DEBUG
    org.wiremock: DEBUG
